name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags --force

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org

      - run: npm install --no-package-lock

      - run: npm run lint

      - run: npm test

      - run: npm run build

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
